In [5]:
import pandas as pd

df=pd.read_csv("C:\\ML Projects\\Credit Scoring\\Credit Score Classification Dataset.csv")

display(df.head())

,Age,Gender,Income,Education,Marital Status,Number of Children,Home Ownership,Credit Score
0,25,Female,50000,Bachelor's Degree,Single,0,Rented,High
1,30,Male,100000,Master's Degree,Married,2,Owned,High
2,35,Female,75000,Doctorate,Married,1,Owned,High
3,40,Male,125000,High School Diploma,Single,0,Owned,High
4,45,Female,100000,Bachelor's Degree,Married,3,Owned,High

In [6]:
print(df.isnull().sum())

Age                   0
Gender                0
Income                0
Education             0
Marital Status        0
Number of Children    0
Home Ownership        0
Credit Score          0
dtype: int64

Missing Value Analysis:
The dataset was checked for missing values using df.isnull().sum(). No missing values were found, so no imputation or row removal was required

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 164 entries, 0 to 163
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Age                 164 non-null    int64
 1   Gender              164 non-null    str
 2   Income              164 non-null    int64
 3   Education           164 non-null    str
 4   Marital Status      164 non-null    str
 5   Number of Children  164 non-null    int64
 6   Home Ownership      164 non-null    str
 7   Credit Score        164 non-null    str
dtypes: int64(3), str(5)
memory usage: 16.3 KB

In [8]:
df.duplicated().sum()

np.int64(62)

In [9]:
print(df.duplicated().sum())

62

In [10]:
df = df.drop_duplicates()

In [11]:
print(df.shape)
print(df.duplicated().sum())

(102, 8)
0

Duplicate Value Handling:
The dataset contained 62 duplicate records. These duplicate rows were removed using drop_duplicates() to improve data quality and prevent bias during model training.

In [13]:
df["Credit Score"].value_counts()

Credit Score
High       75
Average    21
Low         6
Name: count, dtype: int64

In [14]:
from sklearn.preprocessing import LabelEncoder

# Create LabelEncoder
le = LabelEncoder()

# Encode categorical columns
categorical_columns = [
    "Gender",
    "Education",
    "Marital Status",
    "Home Ownership",
    "Credit Score"
]

for col in categorical_columns:
    df[col] = le.fit_transform(df[col])

df.head()

,Age,Gender,Income,Education,Marital Status,Number of Children,Home Ownership,Credit Score
0,25,0,50000,1,1,0,1,1
1,30,1,100000,4,0,2,0,1
2,35,0,75000,2,0,1,0,1
3,40,1,125000,3,1,0,0,1
4,45,0,100000,1,0,3,0,1

In [15]:
df.info()

<class 'pandas.DataFrame'>
Index: 102 entries, 0 to 134
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Age                 102 non-null    int64
 1   Gender              102 non-null    int64
 2   Income              102 non-null    int64
 3   Education           102 non-null    int64
 4   Marital Status      102 non-null    int64
 5   Number of Children  102 non-null    int64
 6   Home Ownership      102 non-null    int64
 7   Credit Score        102 non-null    int64
dtypes: int64(8)
memory usage: 7.2 KB

In [16]:
X = df.drop("Credit Score", axis=1)
y = df["Credit Score"]

print(X.shape)
print(y.shape)

(102, 7)
(102,)

In [17]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print(X_train.shape)
print(X_test.shape)

(81, 7)
(21, 7)

In [18]:
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

In [19]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [20]:
lr_model = LogisticRegression(max_iter=1000)

lr_model.fit(X_train_scaled, y_train)

LogisticRegression(max_iter=1000)

In [22]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [23]:
from sklearn.linear_model import LogisticRegression

lr_model = LogisticRegression(max_iter=1000)

lr_model.fit(X_train_scaled, y_train)

LogisticRegression(max_iter=1000)

In [24]:
y_pred_lr = lr_model.predict(X_test_scaled)

In [25]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

print("Accuracy:", accuracy_score(y_test, y_pred_lr))
print(classification_report(y_test, y_pred_lr))
print(confusion_matrix(y_test, y_pred_lr))

Accuracy: 0.9047619047619048
              precision    recall  f1-score   support

           0       0.75      0.75      0.75         4
           1       0.94      0.94      0.94        16
           2       1.00      1.00      1.00         1

    accuracy                           0.90        21
   macro avg       0.90      0.90      0.90        21
weighted avg       0.90      0.90      0.90        21

[[ 3  1  0]
 [ 1 15  0]
 [ 0  0  1]]

In [26]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Create model
dt_model = DecisionTreeClassifier(random_state=42)

# Train
dt_model.fit(X_train, y_train)

# Predict
y_pred_dt = dt_model.predict(X_test)

# Evaluate
print("Accuracy:", accuracy_score(y_test, y_pred_dt))
print("\nClassification Report:\n")
print(classification_report(y_test, y_pred_dt))
print("\nConfusion Matrix:\n")
print(confusion_matrix(y_test, y_pred_dt))

Accuracy: 1.0

Classification Report:

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         4
           1       1.00      1.00      1.00        16
           2       1.00      1.00      1.00         1

    accuracy                           1.00        21
   macro avg       1.00      1.00      1.00        21
weighted avg       1.00      1.00      1.00        21


Confusion Matrix:

[[ 4  0  0]
 [ 0 16  0]
 [ 0  0  1]]

In [27]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Create model
rf_model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

# Train model
rf_model.fit(X_train, y_train)

# Make predictions
y_pred_rf = rf_model.predict(X_test)

# Evaluate
print("Accuracy:", accuracy_score(y_test, y_pred_rf))

print("\nClassification Report:\n")
print(classification_report(y_test, y_pred_rf))

print("\nConfusion Matrix:\n")
print(confusion_matrix(y_test, y_pred_rf))

Accuracy: 0.9047619047619048

Classification Report:

              precision    recall  f1-score   support

           0       0.75      0.75      0.75         4
           1       0.94      0.94      0.94        16
           2       1.00      1.00      1.00         1

    accuracy                           0.90        21
   macro avg       0.90      0.90      0.90        21
weighted avg       0.90      0.90      0.90        21


Confusion Matrix:

[[ 3  1  0]
 [ 1 15  0]
 [ 0  0  1]]

In [28]:
from sklearn.model_selection import cross_val_score

scores = cross_val_score(
    DecisionTreeClassifier(random_state=42),
    X,
    y,
    cv=5
)

print("Cross Validation Scores:", scores)
print("Average Accuracy:", scores.mean())

Cross Validation Scores: [0.9047619 1.        1.        1.        0.75     ]
Average Accuracy: 0.930952380952381

"The Decision Tree achieved the best performance on this dataset, with 100% accuracy on the test set and an average cross-validation accuracy of 93.1%. Due to the limited dataset size, cross-validation was used to obtain a more reliable estimate of performance."

In [29]:
from sklearn.preprocessing import LabelEncoder

encoders = {}

categorical_columns = [
    "Gender",
    "Education",
    "Marital Status",
    "Home Ownership",
    "Credit Score"
]

for col in categorical_columns:
    encoder = LabelEncoder()
    df[col] = encoder.fit_transform(df[col])
    encoders[col] = encoder

In [30]:
X = df.drop("Credit Score", axis=1)
y = df["Credit Score"]

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

from sklearn.tree import DecisionTreeClassifier

dt_model = DecisionTreeClassifier(random_state=42)

dt_model.fit(X_train, y_train)

DecisionTreeClassifier(random_state=42)

In [31]:
import joblib

joblib.dump(dt_model, "credit_scoring_model.pkl")
joblib.dump(encoders, "label_encoders.pkl")

print("Model and encoders saved successfully!")

Model and encoders saved successfully!

In [32]:
from sklearn.preprocessing import LabelEncoder

encoders = {}

categorical_columns = [
    "Gender",
    "Education",
    "Marital Status",
    "Home Ownership",
    "Credit Score"
]

for col in categorical_columns:
    encoder = LabelEncoder()
    df[col] = encoder.fit_transform(df[col])
    encoders[col] = encoder

joblib.dump(encoders, "label_encoders.pkl")

['label_encoders.pkl']